version: '3.8'

services:
  frontend:
    build: 
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: 
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/finservesolutions
      - INSTANCE_ID=Backend Instance 2
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"  # Port différent pour éviter les conflits
    volumes:
      - mongo_data_instance2:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"  # Port pour Instance 2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  mongo_data_instance2: